leetcode_problems = [
    {'order': 1, 'name': 'Contains Duplicate', 'difficulty': 'Easy', 'leetcode_num': 217, 'done': 'yes'},
    {'order': 2, 'name': 'Missing Number', 'difficulty': 'Easy', 'leetcode_num': 268, 'done': 'yes'},
    {'order': 3, 'name': 'Find All Numbers Disappeared in an Array', 'difficulty': 'Easy', 'leetcode_num': 448, 'done': 'yes'},
    {'order': 4, 'name': 'Two Sum', 'difficulty': 'Easy', 'leetcode_num': 1, 'done': 'yes'},
    {'order': 5, 'name': 'Final Value of Variable After Performing Operations', 'difficulty': 'Easy', 'leetcode_num': 2011, 'done': 'yes'},
    {'order': 6, 'name': 'How Many Numbers Are Smaller Than the Current Number', 'difficulty': 'Easy', 'leetcode_num': 1365, 'done': 'yes'},
    {'order': 7, 'name': 'Minimum Time Visiting All Points', 'difficulty': 'Easy', 'leetcode_num': 1266, 'done': 'yes'},
    {'order': 8, 'name': 'Spiral Matrix', 'difficulty': 'Medium', 'leetcode_num': 54, 'done': 'yes'},
    {'order': 9, 'name': 'Number of Islands', 'difficulty': 'Medium', 'leetcode_num': 200, 'done': 'yes'},
    {'order': 10, 'name': 'Best Time to Buy and Sell Stock', 'difficulty': 'Easy', 'leetcode_num': 121, 'done': 'yes'},
    {'order': 11, 'name': 'Squares of a Sorted Array', 'difficulty': 'Easy', 'leetcode_num': 977, 'done': 'yes'},
    {'order': 12, 'name': '3Sum', 'difficulty': 'Medium', 'leetcode_num': 15, 'done': 'yes'},
    {'order': 13, 'name': 'Longest Mountain in Array', 'difficulty': 'Medium', 'leetcode_num': 845, 'done': 'yes'},
    {'order': 14, 'name': 'Contains Duplicate II', 'difficulty': 'Easy', 'leetcode_num': 219, 'done': 'yes'},
    {'order': 15, 'name': 'Minimum Absolute Difference', 'difficulty': 'Easy', 'leetcode_num': 1200, 'done': 'yes'},
    {'order': 16, 'name': 'Minimum Size Subarray Sum', 'difficulty': 'Medium', 'leetcode_num': 209, 'done': 'yes'},
    {'order': 17, 'name': 'Single Number', 'difficulty': 'Easy', 'leetcode_num': 136, 'done': 'yes'},
    {'order': 18, 'name': 'Coin Change', 'difficulty': 'Medium', 'leetcode_num': 322, 'done': 'yes'},
    {'order': 19, 'name': 'Climbing Stairs', 'difficulty': 'Easy', 'leetcode_num': 70, 'done': 'yes'},
    {'order': 20, 'name': 'Maximum Subarray', 'difficulty': 'Medium', 'leetcode_num': 53, 'done': 'yes'},
    {'order': 21, 'name': 'Counting Bits', 'difficulty': 'Easy', 'leetcode_num': 338, 'done': 'no'},
    {'order': 22, 'name': 'Range Sum Query - Immutable', 'difficulty': 'Easy', 'leetcode_num': 303, 'done': 'no'},
    {'order': 23, 'name': 'Letter Case Permutation', 'difficulty': 'Medium', 'leetcode_num': 784, 'done': 'no'},
    {'order': 24, 'name': 'Subsets', 'difficulty': 'Medium', 'leetcode_num': 78, 'done': 'no'},
    {'order': 25, 'name': 'Combinations', 'difficulty': 'Medium', 'leetcode_num': 77, 'done': 'no'},
    {'order': 26, 'name': 'Permutations', 'difficulty': 'Medium', 'leetcode_num': 46, 'done': 'no'},
    {'order': 27, 'name': 'Middle of the Linked List', 'difficulty': 'Easy', 'leetcode_num': 876, 'done': 'no'},
    {'order': 28, 'name': 'Linked List Cycle', 'difficulty': 'Easy', 'leetcode_num': 141, 'done': 'no'},
    {'order': 29, 'name': 'Reverse Linked List', 'difficulty': 'Easy', 'leetcode_num': 206, 'done': 'no'},
    {'order': 30, 'name': 'Remove Linked List Elements', 'difficulty': 'Easy', 'leetcode_num': 203, 'done': 'no'},
    {'order': 31, 'name': 'Reverse Linked List II', 'difficulty': 'Medium', 'leetcode_num': 92, 'done': 'no'},
    {'order': 32, 'name': 'Palindrome Linked List', 'difficulty': 'Easy', 'leetcode_num': 234, 'done': 'no'},
    {'order': 33, 'name': 'Merge Two Sorted Lists', 'difficulty': 'Easy', 'leetcode_num': 21, 'done': 'no'},
    {'order': 34, 'name': 'Min Stack', 'difficulty': 'Medium', 'leetcode_num': 155, 'done': 'no'},
    {'order': 35, 'name': 'Valid Parentheses', 'difficulty': 'Easy', 'leetcode_num': 20, 'done': 'no'},
    {'order': 36, 'name': 'Evaluate Reverse Polish Notation', 'difficulty': 'Medium', 'leetcode_num': 150, 'done': 'no'},
    {'order': 37, 'name': 'Implement Stack using Queues', 'difficulty': 'Easy', 'leetcode_num': 225, 'done': 'no'},
    {'order': 38, 'name': 'Time Needed to Buy Tickets', 'difficulty': 'Easy', 'leetcode_num': 2073, 'done': 'no'},
    {'order': 39, 'name': 'Reverse First K Elements of Queue', 'difficulty': 'Instructional', 'leetcode_num': 'None', 'done': 'no'},
    {'order': 40, 'name': 'Average of Levels in Binary Tree', 'difficulty': 'Easy', 'leetcode_num': 637, 'done': 'no'},
    {'order': 41, 'name': 'Minimum Depth of Binary Tree', 'difficulty': 'Easy', 'leetcode_num': 111, 'done': 'no'},
    {'order': 42, 'name': 'Maximum Depth of Binary Tree', 'difficulty': 'Easy', 'leetcode_num': 104, 'done': 'no'},
    {'order': 43, 'name': 'Level Order Traversal', 'difficulty': 'Medium', 'leetcode_num': 102, 'done': 'no'},
    {'order': 44, 'name': 'Same Tree', 'difficulty': 'Easy', 'leetcode_num': 100, 'done': 'no'},
    {'order': 45, 'name': 'Path Sum', 'difficulty': 'Easy', 'leetcode_num': 112, 'done': 'no'},
    {'order': 46, 'name': 'Diameter of Binary Tree', 'difficulty': 'Easy', 'leetcode_num': 543, 'done': 'no'},
    {'order': 47, 'name': 'Invert Binary Tree', 'difficulty': 'Easy', 'leetcode_num': 226, 'done': 'no'},
    {'order': 48, 'name': 'Lowest Common Ancestor of a Binary Tree', 'difficulty': 'Medium', 'leetcode_num': 236, 'done': 'no'},
    {'order': 49, 'name': 'Search in a Binary Search Tree', 'difficulty': 'Easy', 'leetcode_num': 700, 'done': 'no'},
    {'order': 50, 'name': 'Insert into a Binary Search Tree', 'difficulty': 'Medium', 'leetcode_num': 701, 'done': 'no'},
    {'order': 51, 'name': 'Convert Sorted Array to Binary Search Tree', 'difficulty': 'Easy', 'leetcode_num': 108, 'done': 'no'},
    {'order': 52, 'name': 'Two Sum IV - Input is a BST', 'difficulty': 'Easy', 'leetcode_num': 653, 'done': 'no'},
    {'order': 53, 'name': 'Lowest Common Ancestor of a BST', 'difficulty': 'Easy', 'leetcode_num': 235, 'done': 'no'},
    {'order': 54, 'name': 'Minimum Absolute Difference in BST', 'difficulty': 'Easy', 'leetcode_num': 530, 'done': 'no'},
    {'order': 55, 'name': 'Balance a Binary Search Tree', 'difficulty': 'Medium', 'leetcode_num': 1382, 'done': 'no'},
    {'order': 56, 'name': 'Delete Node in a BST', 'difficulty': 'Medium', 'leetcode_num': 450, 'done': 'no'},
    {'order': 57, 'name': 'Kth Smallest Element in a BST', 'difficulty': 'Medium', 'leetcode_num': 230, 'done': 'no'},
    {'order': 58, 'name': 'Kth Largest Element in an Array', 'difficulty': 'Medium', 'leetcode_num': 215, 'done': 'no'},
    {'order': 59, 'name': 'K Closest Points to Origin', 'difficulty': 'Medium', 'leetcode_num': 973, 'done': 'no'},
    {'order': 60, 'name': 'Top K Frequent Elements', 'difficulty': 'Medium', 'leetcode_num': 347, 'done': 'no'},
    {'order': 61, 'name': 'Task Scheduler', 'difficulty': 'Medium', 'leetcode_num': 621, 'done': 'no'},
    {'order': 62, 'name': 'Clone Graph', 'difficulty': 'Medium', 'leetcode_num': 133, 'done': 'no'},
    {'order': 63, 'name': 'Cheapest Flights Within K Stops', 'difficulty': 'Medium', 'leetcode_num': 787, 'done': 'no'},
    {'order': 64, 'name': 'Course Schedule', 'difficulty': 'Medium', 'leetcode_num': 207, 'done': 'no'},
]
